DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
HTTP_PORT: 3000
BASE_DATABASE_URL: postgres://postgres:postgres@localhost:5432
DATABASE_NAME: test_db
DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable
REDIS_URL: redis://localhost:6379/0
# GIN_ENV: production
GIN_ENV: development
