apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pangu
spec:
  selector:
    matchLabels:
      app: go-pangu
  template:
    metadata:
      labels:
        app: go-pangu
    spec:
      containers:
      - name: go-pangu
        image: go-pangu
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: go-pangu-np-service
spec:
  selector:
    app: go-pangu
  type: NodePort
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30080
