version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  server:
    image: go-pangu
    ports:
      - "80:3002"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
volumes:
  pgdata:
  redisdata:
