DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
HTTP_PORT: 3000
DATABASE_URL: postgres://postgres:postgres@localhost:5432/development?pool=25&encoding=unicode&schema_search_path=public
REDIS_URL: redis://localhost:6379/0
